.input numParticipants `repeat_iter([(num_participants,),])`

.async voteFromParticipant `null::<(u32,u32,)>()` `source_stream(from_participant_source) -> map(|v| deserialize_from_bytes::<(u32,u32,)>(v.unwrap()).unwrap())`
        
allVotes(l, v) :- voteFromParticipant(l, v)
allVotes(l, v) :+ allVotes(l, v), !committed(v)
voteCounts(count(l), v) :- allVotes(l, v)
committed(v) :- voteCounts(n, v), numParticipants(n)