.input myID `repeat_iter([(my_id,),])`
.input numCollectorPartitions `repeat_iter([(num_collector_partitions,),])` # Assume id = 0,1,2...

.async voteToParticipant `null::<(u32,)>()` `source_stream(to_participant_source) -> map(|x| deserialize_from_bytes::<(u32,)>(x.unwrap()).unwrap())`
.async voteFromParticipant `map(|(node_id, v)| (node_id, serialize_to_bytes(v))) -> dest_sink(from_participant_sink)` `null::<(u32,u32,)>()`
            
voteFromParticipant@(v%n)(i, v) :~ voteToParticipant(v), numCollectorPartitions(n), myID(i)