.input leader `repeat_iter(peers.clone()) -> map(|p| (p,))`
.async toReplica `null::<(u32,u32,)>()` `source_stream(to_replica_source) -> map(|x| deserialize_from_bytes::<(u32,u32)>(x.unwrap()).unwrap())`
.async fromReplica `map(|(node_id, v)| (node_id, serialize_to_bytes(v))) -> dest_sink(from_replica_sink)` `null::<(u32,u32,)>()`

.persist storage
storage(v) :- toReplica(v) 
fromReplica@addr(i, v) :~ toReplica(v), leader(addr), myID(i)