######################## relation definitions
# EDB
.input clientIn `repeat_iter_external(vec![()]) -> map(|_| (context.current_tick() as u32, context.current_tick() as u32))`
.input numVoteRequesters `repeat_iter(num_vote_requester_partitions.clone()) -> map(|p| (p,))`

.async voteToVoteRequester `map(|(node_id, v):(u32,(u32,u32))| (node_id, serialize_to_bytes(v))) -> dest_sink(vote_to_vote_requester_sink)` `null::<(u32,u32,)>()`
######################## end relation definitions

# Phase 1a
voteToVoteRequester@(tid%n)(tid, p) :~ clientIn(tid, p), numVoteRequesters(n)