.input myID `repeat_iter(my_id.clone()) -> map(|p| (p,))`
.input leader `repeat_iter(peers.clone()) -> map(|p| (p,))`
.async voteToReplica `null::<(u32,i64,Rc<Vec<u8>>,)>()` `source_stream(to_replica_source) -> map(|x| deserialize_and_hash(deserialize_from_bytes::<(u32,i64,Rc<Vec<u8>>,)>(x.unwrap().1).unwrap()))`
.async voteFromReplica `map(|(node_id, v)| (node_id, serialize_to_bytes(v))) -> dest_sink(from_replica_sink)` `null::<(u32,u32,i64,Rc<Vec<u8>>,)>()`
            
.persist storage
storage(v, hashed) :+ voteToReplica(client, id, v, hashed)
collisions(choose(v2), hashed) :- voteToReplica(client, id, v1, hashed), storage(v2, hashed)
voteFromReplica@addr(i, client, id, v2) :~ voteToReplica(client, id, v, hashed), collisions(v2, hashed), leader(addr), myID(i)
voteFromReplica@addr(i, client, id, v) :~ voteToReplica(client, id, v, hashed), !collisions(_, hashed), leader(addr), myID(i)